server:
<<<<<<< HEAD
  port: 8761

spring:
  application:
    name: registry-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
=======
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jakemateharol/delivery-config-repo.git
          default-label: main
          clone-on-start: true
>>>>>>> bbad99116a814b754cc43a4e68fad37d9b951889
